// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127145200_SeedIngredients")]
    partial class SeedIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3eadde6e-6553-466f-944d-4619638bdcde"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(8962),
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("5ee86808-027e-4821-9dbc-c7e7e474c68f"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(8971),
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("4065924a-9276-449b-a4a8-3613d6902e6d"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(8973),
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = new Guid("45960150-22bc-4373-9774-936d8649e3be"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(8974),
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = new Guid("703194bf-433f-42fb-ba97-fd7bf2da79c7"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(8976),
                            Name = "Snack"
                        },
                        new
                        {
                            Id = new Guid("1cc14a78-acfd-45fd-9f62-019d11fbd84a"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(8977),
                            Name = "Beverage"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20e34178-e4b5-437d-b433-d9f5401c28fc"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9134),
                            Name = "Pasta",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("71392fb4-bce4-45b2-87e9-1d8bdcc5f964"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9136),
                            Name = "Rice",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("033f85a3-ed49-4904-84b5-d3ad3e7cf64b"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9137),
                            Name = "Butter",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("2410c70c-b047-490d-bbef-cb1747976866"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9138),
                            Name = "Olive Oil",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = new Guid("7572461c-25dd-4fed-beb6-ad24d56a496e"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9140),
                            Name = "Parmesan",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("1f79f995-5c70-458a-9652-1fa1f67b04fe"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9141),
                            Name = "Garlic",
                            Unit = "cloves"
                        },
                        new
                        {
                            Id = new Guid("874c853a-6c8b-43ff-9472-ad0348a5e57c"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9142),
                            Name = "Onion",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("1479d39f-1c79-45fd-afa2-bb1b310d3c44"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9143),
                            Name = "Tomato",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("775b8a55-790d-4d73-8bd3-366924668c08"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9146),
                            Name = "Chicken Breast",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("4e4a0dcc-121f-4154-a54d-a58a968bd629"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9148),
                            Name = "Eggs",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("cca0d0c1-06c6-4d97-aac7-76dfb24cf3ab"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9149),
                            Name = "Flour",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("59774212-5dfe-4c3e-851b-542c25d58070"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9150),
                            Name = "Sugar",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("5c36a30f-7d23-4980-af67-15568ad028c9"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9151),
                            Name = "Salt",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("8a48d6f1-152e-4615-b58d-2f70343aa0ef"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9153),
                            Name = "Black Pepper",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("0031fc49-bffa-43bf-a3ac-186747d5a30d"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 52, 0, 46, DateTimeKind.Utc).AddTicks(9154),
                            Name = "Milk",
                            Unit = "ml"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
