// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205143732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c694ec3-9735-4ce0-b7b8-241fc0990b0c"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7274),
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("07e17bcd-b2c6-405a-ba83-a28b9815799a"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7279),
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("f84d56cd-5d4c-4b2a-acc9-b85cf48c881d"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7281),
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = new Guid("71a588c0-3cba-477a-9dbf-72e935e4b905"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7282),
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = new Guid("20a3da38-9bb6-4856-b15c-250b2cc86811"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7299),
                            Name = "Snack"
                        },
                        new
                        {
                            Id = new Guid("451028ec-8a05-4a05-a45f-17689585f758"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7301),
                            Name = "Beverage"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11d05171-ed14-4b50-a0c4-7e5d61d88f0f"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7481),
                            Name = "Pasta",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("8cd6b4fd-9cbf-4c33-948c-309ed277ee3e"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7482),
                            Name = "Rice",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("e7ca2aa1-faf1-4ec7-9a0c-0ec523ce2620"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7486),
                            Name = "Butter",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("3c2ff29f-8e44-42a3-b50f-f410c7e179fc"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7488),
                            Name = "Olive Oil",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = new Guid("927d9a6e-3f51-4353-8a7d-5d7884f36185"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7489),
                            Name = "Parmesan",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("11005718-e8d6-4373-bd25-c9aad043bb5a"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7490),
                            Name = "Garlic",
                            Unit = "cloves"
                        },
                        new
                        {
                            Id = new Guid("bda56feb-6825-46f5-a678-b29dd14498c5"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7492),
                            Name = "Onion",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("8be265c9-f329-4e62-873f-cd71bae01b70"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7493),
                            Name = "Tomato",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("dfb950b7-30ff-4afd-9ec6-59be0a7211da"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7494),
                            Name = "Chicken Breast",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("65599b80-9e5d-4e35-a06b-afe9b7f2ab4d"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7495),
                            Name = "Eggs",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("a4383a22-8f91-42bb-bb06-f511f81b9cdb"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7498),
                            Name = "Flour",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("128e7dc4-6bc3-4ec2-9d9d-bad88b7e50a5"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7499),
                            Name = "Sugar",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("ec4cdf63-517a-4772-ad0d-a4f34d554ff7"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7501),
                            Name = "Salt",
                            Unit = "to taste"
                        },
                        new
                        {
                            Id = new Guid("6f2dd2b8-f0e7-40ae-a63d-1152b4b940b4"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7502),
                            Name = "Black Pepper",
                            Unit = "to taste"
                        },
                        new
                        {
                            Id = new Guid("cc1c3adb-b65f-4afe-b2c8-14d6f5eb34fb"),
                            CreatedAt = new DateTime(2025, 12, 5, 14, 37, 32, 635, DateTimeKind.Utc).AddTicks(7503),
                            Name = "Milk",
                            Unit = "ml"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
