// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8c5c8d1-d30a-4fc0-bbc6-3261e9c6ec6d"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4429),
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("5347112c-b575-4622-a1b6-9f78e6011c9b"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4432),
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("97dc1f0f-59c7-4799-8a37-8497571317f2"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4434),
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = new Guid("39c8c5d4-2add-436c-85a2-a2f5fab7b1b5"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4436),
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = new Guid("aa86adc2-3b96-442b-8aee-b9442f0260b6"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4437),
                            Name = "Snack"
                        },
                        new
                        {
                            Id = new Guid("877eb676-72dc-4e0e-919e-76c39176492f"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4438),
                            Name = "Beverage"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04e395ee-ebce-4b69-a55d-0fc3d009adbe"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4590),
                            Name = "Pasta",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a137ae52-5619-4304-95d8-786999f22f84"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4598),
                            Name = "Rice",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("c562328f-a8da-4b28-af7b-249bded9783e"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4599),
                            Name = "Butter",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("3c2cd2b5-b743-4eef-bd94-8c37d9ea65ed"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4600),
                            Name = "Olive Oil",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = new Guid("d9a5e786-4802-4b7d-8b9d-08e9380d3def"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4601),
                            Name = "Parmesan",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("62fd9996-37e9-4cc6-8adf-61963dd82ef1"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4603),
                            Name = "Garlic",
                            Unit = "cloves"
                        },
                        new
                        {
                            Id = new Guid("f34235a0-85a2-4e73-a7a4-cb79e4285694"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4604),
                            Name = "Onion",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("bee4b68d-22e6-4b40-bd38-d7606961c202"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4605),
                            Name = "Tomato",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("3210bedb-a78e-4763-af7b-8f7da3be1165"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4606),
                            Name = "Chicken Breast",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("aa38523a-b5b3-41ff-b434-4ff6ecf648ea"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4610),
                            Name = "Eggs",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = new Guid("eff3e8ca-bb4c-4526-8834-eb1c66190a6e"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4611),
                            Name = "Flour",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("f6163d7a-ab45-4209-bc8e-84a6c8846f2d"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4612),
                            Name = "Sugar",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("2b6c80dd-6889-4260-9db8-09a73be7e785"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4613),
                            Name = "Salt",
                            Unit = "to taste"
                        },
                        new
                        {
                            Id = new Guid("bf65a7ea-fa55-43c7-a712-f13217fa530a"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4615),
                            Name = "Black Pepper",
                            Unit = "to taste"
                        },
                        new
                        {
                            Id = new Guid("315a6151-3df9-40bc-8bf2-6152c1b200a9"),
                            CreatedAt = new DateTime(2025, 12, 4, 9, 45, 37, 583, DateTimeKind.Utc).AddTicks(4616),
                            Name = "Milk",
                            Unit = "ml"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Domain.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
